// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(grunt) {
    var coffeeify, stringify;
    stringify = require('stringify');
    coffeeify = require('coffeeify');
    grunt.initConfig({
        connect: {
            server: {
                options: {
                    port: 8000,
                    open: true
                }
            }
        },
      copy: {
        dev: {
          files: [
            {
              src: ["lib/jquery/dist/jquery.min.js"],
              dest: 'dist/lib/jquery.min.js'
            }, {
              src: ["lib/jquery/dist/jquery.min.map"],
              dest: 'dist/lib/jquery.min.map'
            }, {
              src: ["lib/unslider.js"],
              dest: 'dist/lib/unslider.js'
            }
          ]
        }
      },
      clean: {
        dist: ['dist']
      },
        browserify: {
            components: {
                options: {
                    preBundleCB: function(b) {
                        b.transform(coffeeify);
                        return b.transform(stringify({
                            extensions: ['.hbs', '.html', '.tpl', '.txt']
                        }));
                    }
                },
                expand: true,
                flatten: true,
                files: {
                    'dist/js/main.js': ['src/main.js']
                }
            }
        },
      watch: {
        compile: {
          files: ['src/**/*.less', 'src/**/*.js'],
          tasks: ['browserify', 'less']
        }
      },
      less: {
        components: {
          files: {
            'dist/css/layout.css': ['src/templates/components/**/*.less', 'src/common/**/*.less']
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-connect');
    grunt.loadNpmTasks('grunt-browserify');
    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-watch');
    return grunt.registerTask('default', function() {
      return grunt.task.run(['less','browserify', 'connect', 'watch']);
    });
  };

}).call(this);
